stan-dev/example-models

ARM/Ch.7/7.1_SimulationOfProbabilityModels.R
ARM/Ch.7/7.2_SummarizingLinearRegressionUsingSimulation.R

I'm working through the Gelman/Hill book using the ARM examples. I've caught a couple of typos (numbers that don't match the text of the book).

numerical typos in ARM examples

---

knitr/pool-repeated-trials/pool-no-pool.Rmd

@bob-carpenter I was going over this again in order to see if I could fit these models (or similar ones) in rstanarm and I couldn’t help myself from making a few changes to the R code. I figured I’d do this as a pull request so you can either decide you want to use these changes and merge it or just close the pull request if you prefer to leave the code as is.
Summary: 
* re-use a single function for all of the similar scatterplots
* use greek letters in axis labels where appropriate
* simplify data creation and plotting code for bda_5_4 figure (the plot of observed vs estimated success rate with 80% intervals)
* remove one section where the same data frame is created twice

knitr pooling R code edits

---

BPA/Ch.12/12.3.1_Simple_Poisson_model.R
BPA/Ch.12/12.3.2_Zero-Inflated.R
BPA/Ch.12/12.3.3_Overdispersion.R
BPA/Ch.12/Nmix0.stan
BPA/Ch.12/Nmix1.stan
BPA/Ch.12/Nmix2.stan
BPA/README.md

I add models in Section 12.3 of BPA. This is the final section to complete the translation. Would you please review the code?

BPA: Add Section 12.3 (final)

---

Bayesian_Cognitive_Modeling/ParameterEstimation/Binomial/Survey_Stan.R

One of the Binomial models had a misspecified file name in the R script.

fixed name of model file in R script

---

BPA/Ch.03/GLM_Binomial.stan
BPA/Ch.03/GLM_Poisson.stan

I updated Stan files using Stan 2.10 syntax. Would you review the codes?

BPA Ch.03: Stan 2.10 syntax

---

BPA/Ch.05/ssm.stan
BPA/Ch.05/ssm2.stan
BPA/Ch.06/6.3_Real_data_set.R
BPA/Ch.06/M0.stan
BPA/Ch.06/Mb.stan
BPA/Ch.06/Mh.stan
BPA/Ch.06/Mt.stan
BPA/Ch.06/MtX.stan
BPA/Ch.06/Mtbh.stan
BPA/Ch.06/Mth.stan

BPA/Ch.05 & Ch.06 update

---

BPA/Ch.08/8.2.2_State-space.R
BPA/Ch.08/8.3.1_Constant_parameters.R
BPA/Ch.08/8.3.2_Age-dependent.R
BPA/Ch.08/8.4_Real_data.R
BPA/Ch.08/mr_mnl.stan
BPA/Ch.08/mr_mnl_age.stan
BPA/Ch.08/mr_mnl_age3.stan
BPA/Ch.08/mr_ss.stan

I updated the models in Chapter 8 of BPA. Would you review the code?

BPA Ch.08 Update

---

BPA/Ch.09/9.2_Movement_between_two_sites.R
BPA/Ch.09/9.3_Temporary_emigration.R
BPA/Ch.09/9.4_First_breeding.R
BPA/Ch.09/9.5_Joint_analysis.R
BPA/Ch.09/9.6_Three_sites.R
BPA/Ch.09/9.7_Real_data.R
BPA/Ch.09/agerecruitment.stan
BPA/Ch.09/ladyslipper.stan
BPA/Ch.09/lifedead.stan
BPA/Ch.09/ms.stan
BPA/Ch.09/ms3_multinomlogit.stan
BPA/Ch.09/ms_alternative1.stan
BPA/Ch.09/ms_alternative2.stan
BPA/Ch.09/tempemi.stan

I updated the models in the Chapter 9. Would you review the code?

BPA Ch.09 update

---

knitr/mle-params/mle-params.Rmd

Copyright by Stijn de Waele. I agree to license under BSD for the code, and CC-BY for the text.

mle-params: Describe distinction between posterior mode and ML estimator

---

BPA/Ch.13/site-occ_cov.stan

I updated a site-occupancy model to improve accuracy of an estimate. Would you review the code?

BPA/Ch.13 Update a site-occupancy model

---

BPA/Ch.07/7.10.3_Age-dependent_models.R

Correspondences between R and Stan files were wrong in Chapter 7.

BPA: Fix mistakes in R files

---

BPA/Ch.06/6.2.4_Model_Mh.R
BPA/Ch.06/6.2.5_Model_Mth.R
BPA/Ch.06/6.3_Real_data_set.R
BPA/Ch.06/6.4_Model_MtX.R
BPA/Ch.06/M0.stan
BPA/Ch.06/Mb.stan
BPA/Ch.06/Mh.stan
BPA/Ch.06/Mt.stan
BPA/Ch.06/MtX.stan
BPA/Ch.06/Mtbh.stan
BPA/Ch.06/Mth.stan

Non-centered parameterization is applied for hierarchical models.

Update models in Ch.06 of BPA

---

BPA/Ch.12/Nmix1.stan

I removed the redundant calculation of zero-inflation. It is calculated later in the model.

BPA: update a model

---

misc/gaussian-process/gp-predict-analytic.stan

this should be more efficient since mdivide_ is expensive.

revised to only use two mdivide_ calls

---

misc/ecology/occupancy/occupancy.stan

@bob-carpenter Thank you for catching the extra semi-colon. I removed it.

removed extra semi-colon

---

BPA/Ch.10/js_super.stan
BPA/Ch.10/js_super_indran.stan

bug fix for https://github.com/stan-dev/example-models/issues/146.
Thanks to njhostet for finding the bug and proposing the fixing code.

bug fix for issue #146

---

misc/ecology/mark-recapture/cjs-K.stan
misc/ecology/mark-recapture/cjs.stan
misc/ecology/mark-recapture/mark-recapture-2.stan
misc/ecology/mark-recapture/mark-recapture-3.stan

@bob-carpenter I am trying to use these for a different project. I replaced `<-` with `=` and changed the code to use `target +=` syntax.

updated mark recapture examples

---

BPA/Ch.12/12.2.2_Covariates.R

Update 12.2.2_Covariates.R to include the covariate data (X) in the stan call

Update  12.2.2_Covariates.R

---

basic_estimators/normal_mixture.stan

Changed ``<-`` to ``=``, ``normal_log`` to ``normal_lpdf`` and ``increment_log_prob`` to ``target +=``

Updated the deprecated syntax

---

basic_estimators/normal_mixture.stan

Now using log_mix which allowed the deletion of transformed parameters block.

Updated the stan syntax to use log_mix

---

regression_tests/mother.stan

Update mother model to include all changes made in Stanc3 repo mother model, and tests for user defined `_rng` and `_lp` calls.

update mother model

---

BPA/Ch.13/Dynocc.stan
BPA/Ch.13/Dynocc2.stan

I added some comments to the models.

BPA: add comments

---

knitr/disease_transmission/biblio.bib
knitr/disease_transmission/boarding_school_case_study.Rmd
knitr/disease_transmission/sir_negbin.stan
knitr/disease_transmission/sir_prior.stan
knitr/disease_transmission/sir_simu.stan

- added ‘biblio.bib’
- corrected data section in Stan files
- alternated SIR formulation for better readability 
- added comment on the efficiency in case of the constant total population

corrections

---

knitr/reduce-sum/reduce_sum_tutorial.Rmd

Fixes #175 
The associated website pull request is [here](https://github.com/stan-dev/stan-dev.github.io/pull/115).
Edit: Added link to website repo pull

Updated reduce_sum tutorial for cmdstanr threading interface chanes (Issue #175)

---

knitr/reduce-sum/reduce_sum_tutorial.Rmd

Switched the tutorial to use cores/chains instead of num_cores/num_chains.

Changed num_cores/num_chains to cores/chains

---

knitr/disease_transmission/boarding_school_case_study.Rmd

Fix mistakes and add a link to source code

update the disease transmission case study

---

knitr/reduce-sum/reduce_sum_tutorial.Rmd

This updates to track the new threading/cores/chains stuff: https://github.com/stan-dev/cmdstanr/pull/185

Updated reduce_sum tutorial for latest cmdstanr changes

---

knitr/reduce-sum/logistic1.stan
knitr/reduce-sum/reduce_sum_tutorial.Rmd

~~I'm leaving this as a draft until the rest of the `lupmf` docs get in (this will need to link to them)~~
Skip that just gonna finish this up and get it updated so it does't get forgotten

Updated `reduce_sum` docs to reflect addition of `lupmf`

---

ARM/Ch.3/kidiq_interaction.stan
ARM/Ch.3/kidiq_multi_preds.stan
ARM/Ch.3/kidiq_prediction.stan
ARM/Ch.3/kidiq_validation.stan
ARM/Ch.3/kidscore_momhs.stan
ARM/Ch.3/kidscore_momiq.stan

Updates the Stan syntax in the ARM Ch.3 folder (all changes are pretty much just using the ```normal_id_glm``` distribution)

ARM Ch.3 Models Update

---

ARM/Ch.5/nes_logit.stan
ARM/Ch.5/separation.stan
ARM/Ch.5/wells_d100ars.stan
ARM/Ch.5/wells_daae_c.stan
ARM/Ch.5/wells_dae.stan
ARM/Ch.5/wells_dae_c.stan
ARM/Ch.5/wells_dae_inter.stan
ARM/Ch.5/wells_dae_inter_c.stan
ARM/Ch.5/wells_dist.stan
ARM/Ch.5/wells_dist100.stan
ARM/Ch.5/wells_interaction.stan
ARM/Ch.5/wells_interaction_c.stan
ARM/Ch.5/wells_predicted.stan
ARM/Ch.5/wells_predicted_log.stan

Updates Stan syntax in ```ARM/Ch.5```

Update ARM Ch.5 Models

---

ARM/Ch.4/earn_height.stan
ARM/Ch.4/kidiq_interaction.stan
ARM/Ch.4/kidiq_interaction_c.stan
ARM/Ch.4/kidiq_interaction_c2.stan
ARM/Ch.4/kidiq_interaction_z.stan
ARM/Ch.4/kidscore_momwork.stan
ARM/Ch.4/log10earn_height.stan
ARM/Ch.4/logearn_height.stan
ARM/Ch.4/logearn_height_male.stan
ARM/Ch.4/logearn_interaction.stan
ARM/Ch.4/logearn_interaction_z.stan
ARM/Ch.4/logearn_logheight.stan
ARM/Ch.4/mesquite.stan
ARM/Ch.4/mesquite_log.stan
ARM/Ch.4/mesquite_va.stan
ARM/Ch.4/mesquite_vas.stan
ARM/Ch.4/mesquite_vash.stan
ARM/Ch.4/mesquite_volume.stan
ARM/Ch.4/nes.stan

Updates example models in ```ARM/Ch.4``` to use ```normal_id_glm```

Update ARM Ch.4 Example Models

---

ARM/Ch.6/earnings1.stan
ARM/Ch.6/earnings2.stan
ARM/Ch.6/wells_logit.stan
ARM/Ch.6/wells_probit.stan

Updates Stan syntax in ```ARM/Ch.6```

Update ARM Ch.6 Models

---

ARM/Ch.7/congress.stan
ARM/Ch.7/earnings1.stan
ARM/Ch.7/earnings2.stan
ARM/Ch.7/earnings_interactions.stan
ARM/Ch.7/wells.stan

Updates ```ARM/Ch.7``` models with ```_glm``` syntax

Updates ARM Ch.7 Models

---

ARM/Ch.8/grades.stan
ARM/Ch.8/roaches.stan
ARM/Ch.8/roaches_overdispersion.stan
ARM/Ch.8/unemployment.stan
ARM/Ch.8/y_x.stan

Updates models in ```ARM/Ch.8``` with ```_glm``` syntax and non-centered parameterisations

Update ARM Ch.8 Models

---

ARM/Ch.9/electric_inter.stan
ARM/Ch.9/electric_supp.stan
ARM/Ch.9/electric_tr.stan
ARM/Ch.9/electric_trpre.stan

Updates ```ARM/Ch.9``` models with ```_glm``` syntax

Update ARM Ch9 models

---

knitr/planetary_motion/planetary_motion.rmd

Fix Hamilton's equations

---

ARM/Ch.10/ideo_interactions.stan
ARM/Ch.10/ideo_reparam.stan
ARM/Ch.10/ideo_two_pred.stan
ARM/Ch.10/sesame_multi_preds_3a.stan
ARM/Ch.10/sesame_multi_preds_3b.stan
ARM/Ch.10/sesame_one_pred_2b.stan
ARM/Ch.10/sesame_one_pred_a.stan
ARM/Ch.10/sesame_one_pred_b.stan
ARM/Ch.12/radon_complete_pool.stan
ARM/Ch.12/radon_group.stan
ARM/Ch.12/radon_group_chr.stan
ARM/Ch.12/radon_intercept.stan
ARM/Ch.12/radon_intercept_chr.stan
ARM/Ch.12/radon_no_pool.stan
ARM/Ch.12/radon_no_pool_chr.stan

This PR updates the models in ARM Ch.10 through Ch.12 models to use modern Stan syntax

Updates ARM Ch10-Ch12 models

---

knitr/dynamic-opinion/ClaassenBib.bib
knitr/dynamic-opinion/Support for democracy edit 1122.csv
knitr/dynamic-opinion/dynamic_crossnat_latent_opinion_model.stan
knitr/dynamic-opinion/estimating dynamic latent opinion.Rmd

Adding the materials for @cbpclaassen's case study (https://github.com/stan-dev/stan-dev.github.io/pull/196) with their permission to host them in example-models.

materials for dynamic option case study

---

BPA/Ch.10/js_ms.stan
BPA/Ch.10/js_rest_occ.stan
BPA/Ch.10/js_super.stan
BPA/Ch.10/js_super_indran.stan
BPA/Ch.10/js_tempran.stan

Added explanations on the generation of posterior predictive distribution

Add comments

---

BPA/Ch.10/js_ms.stan
BPA/Ch.10/js_rest_occ.stan
BPA/Ch.10/js_super.stan
BPA/Ch.10/js_super_indran.stan
BPA/Ch.10/js_tempran.stan

delete "unconditioned on the observation" in the comments

Correct comments
